export const SET_TOOL = 'SET_TOOL'
export const SET_CURRENT_PTNUM = 'SET_CURRENT_PTNUM'

export const CREATE_PADS = 'CREATE_PADS'
export const CREATE_POINTS = 'CREATE_POINTS'
export const ADD_CONNECTION = 'ADD_CONNECTION'

export const CREATE_HEADER = 'CREATE_HEADER'
export const SETUP_BOARD = 'SETUP_BOARD'

export const SET_WIRE_COLOR = 'SET_WIRE_COLOR'


